# apiVersion: v1
# kind: ReplicationController
# metadata:
#  name: edgeserver
#  namespace: default
# spec:
#   replicas: 1
#   selector:
#     app: edgeserver
#   template:
#     metadata:
#       labels:
#         app: edgeserver
#     spec:   
#       containers:
#         - name: edgeserver
#           image: app:latest
#           imagePullPolicy: Never
#           ports:
#           - name: http-server
#             containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: edgeserver1
 labels:
    app: edgeserver1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edgeserver1
  template:
    metadata:
      labels:
        app: edgeserver1
    spec:   
      containers:
        - name: edgeserver1
          image: app:latest
          imagePullPolicy: Never
          ports:
          - name: http-server
            containerPort: 8001

---
# apiVersion: v1
# kind: Pod
# metadata:
#  name: edgeserver1
#  namespace: default
# spec:
#   replicas: 1
#   selector:
#     app: edgeserver1
#   template:
#     metadata:
#       labels:
#         app: edgeserver1
#     spec:   
#       containers:
#         - name: edgeserver1
#           image: redis:latest
#           imagePullPolicy: Never
#           ports:
#           - name: http-server
#             containerPort: 8001